---
- name: Delete default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx restart
- name: Create config for wordpress site
  template: "src=nginx.conf dest=/etc/nginx/sites-enabled/{{ php_base_name }}.conf"
  notify: nginx restart

