- name: Ensure packages needed for nginx+php-fpm are present
  apt: name={{ item }} state=present
  with_items:
    - php5-fpm
- name: Ensure that php_user exists
  user:
    name: "{{ php_user }}"
    createhome: no
    shell: /bin/bash
